name: Monitorear Aspen FM

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Actualizado para evitar advertencias

      - name: Ejecutar Monitoreo
        run: node index.js

      - name: Guardar Cambios de Memoria
        run: |
          git config --global user.name 'Aspen Bot'
          git config --global user.email 'bot@aspen.com'
          touch ultimo_tema.txt # Asegura que el archivo exista antes de agregarlo
          git add ultimo_tema.txt
          git diff --quiet && git diff --cached --quiet || (git commit -m "Actualizar último tema escuchado" && git push)
